version: '3.4'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SQLCONNECTION=Server=cresoft.top;Database=AnNhau;User Id=sa;Password=Buiyen123>;TrustServerCertificate=True"
      - "UserEmail=buiyen.cresoft@gmail.com"
      - "PassEmail=bfxbgmdjwjsmwiyt"
    ports:
      - "7414:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro